### ISSUE TITLE
Android - java.lang.NullPointerException

### ISSUE THREAD

**Issue by datomnurdin** [bytefish/facerec#25]
As per subject, I got this error message when i trying to capture or select images from the gallery, then it crash.

```
06-12 04:05:57.152    2243-2243/org.bytefish.facerecapp.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.bytefish.facerecapp.app, PID: 2243
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bytefish.facerecapp.app/org.bytefish.facerecapp.app.RecognitionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
            at org.bytefish.facerecapp.app.RecognitionActivity.onCreate(RecognitionActivity.java:41)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Please advice. Thank. you.

**Comment by bytefish** [comment]
Sorry for my very late reply. The app was just a small test, which never worked as expected. I am going to delete the folder and close this issue accordingly.

**Comment by bytefish** [comment]
The folder and app have been deleted.
