### ISSUE TITLE
Casting error in lbp.py

### ISSUE THREAD

**Issue by arassadin** [bytefish/facerec#35]
Found in: d866ef68ffe96de11e164493d29cc4b124cf7844
```
MY_FR_STUFF raised unexpected: TypeError("Cannot cast ufunc add output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  MY_FR_STUFF, in train
    model.train(images, labels)
  MY_FR_STUFF, in train
    self.model.compute(imgpp, labels)
  File "/usr/local/lib/python2.7/dist-packages/facerec/model.py", line 21, in compute
    features = self.feature.compute(X,y)
  File "/usr/local/lib/python2.7/dist-packages/facerec/feature.py", line 245, in compute
    h = self.spatially_enhanced_histogram(x)
  File "/usr/local/lib/python2.7/dist-packages/facerec/feature.py", line 255, in spatially_enhanced_histogram
    L = self.lbp_operator(X)
  File "/usr/local/lib/python2.7/dist-packages/facerec/lbp.py", line 97, in __call__
    result += (1<<i)*D
TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'
```
Images  - `list` of `np.ndarray` (output from **cv2.imread()** and similar)
Labels - `list` of `string`
Data by itself looks ok.

Appears non-permanent. **Maybe some checks or casts should be added?**

Possible workaround:
```
result += ((1<<i)*D).astype(np.uint32)
```
or about.

**Comment by arassadin** [comment]
NumPy version: 1.10.4
