### ISSUE TITLE
ValueError: X.shape[1] = 360 should be equal to 39, the number of features at training time

### ISSUE THREAD

**Issue by adwidianjaya** [bytefish/facerec#55]
Hi, I replace NN classifier with provided SVM. However I got this error:

```sh
2017-01-14 14:18:01,340 - facerec.validation.KFoldCrossValidation - INFO - Processing fold 1/10.
Traceback (most recent call last):
  File "svm_example.py", line 138, in <module>
    cv.validate(X, y)
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/validation.py", line 217, in validate
    prediction = self.model.predict(X[j])[0]
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/model.py", line 26, in predict
    return self.classifier.predict(q)
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/classifier.py", line 180, in predict
    results = self.svm.predict_proba(y)[0]
NameError: global name 'y' is not defined
```

It seems, y wasn't defined before in predict(self, X) function of SVM classifier. However, I tried to replace y with self.y, since it was defined before in compute function. Then I got this error:

```sh
2017-01-14 14:14:22,118 - facerec.validation.KFoldCrossValidation - INFO - Processing fold 1/10.
/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
Traceback (most recent call last):
  File "svm_example.py", line 138, in <module>
    cv.validate(X, y)
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/validation.py", line 217, in validate
    prediction = self.model.predict(X[j])[0]
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/model.py", line 26, in predict
    return self.classifier.predict(q)
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/facerec/classifier.py", line 180, in predict
    results = self.svm.predict_proba(self.y)[0]
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/sklearn/svm/base.py", line 619, in _predict_proba
    X = self._validate_for_predict(X)
  File "/Users/adhe/.virtualenvs/cv/lib/python2.7/site-packages/sklearn/svm/base.py", line 479, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 360 should be equal to 39, the number of features at training time
```

I have no idea what happens. Any helps? Thanks.

**Comment by bytefish** [comment]
Thanks for reporting. Yes, the SVM implementation wasn't working correctly. I have fixed the problems and also fixed the grid_search used in the facerec.svm module. I have also added a script ``svm_example.py``, which shows how to use the SVM classifier.

The best set of parameters are not automatically set for the classifier, they are only printed out to the console and need to be set manually.

```python
    # Define the Fisherfaces as Feature Extraction method:
    feature = Fisherfaces()
    # Define a 1-NN classifier with Euclidean Distance:
    classifier = SVM()
    # Define the model as the combination
    model = PredictableModel(feature=feature, classifier=classifier)
    # Perform a Grid Search for the Set of Parameters:
    tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
        'C': [1, 10, 100, 1000]},
        {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
    # Find a good set of parameters:
    grid_search(model, X, y, tuned_parameters)
    # Perform a 10-fold cross validation
    cv = KFoldCrossValidation(model, k=10)
    cv.validate(X, y)
    # And print the result:
    cv.print_results()
```

**Comment by bytefish** [comment]
I have fixed the Serialization. Now it is possible to store the computed model.

**Comment by adwidianjaya** [comment]
Thank you so much @bytefish
