### ISSUE TITLE
I get the following error when I run the train command.

### ISSUE THREAD

**Issue by Anish-Jain** [bytefish/facerec#58]
I'm using a Raspberry Pi - 3 Model B, running Raspbian Jessie, Python 2.7, and OpenCV-3.2.0.
Also, I'm using a virtual environment.

I'm getting the following error when run the train command -

(cv) pi@raspberrypi:~/facerec/py/apps/videofacerec $ python simple_videofacerec.py -t /home/pi/Teachers my_model.pkl
Traceback (most recent call last):
File "simple_videofacerec.py", line 16, in <module>
from facerec.model import PredictableModel
File "../../facerec/model.py", line 7, in <module>
from facerec.feature import AbstractFeature
File "../../facerec/feature.py", line 44, in <module>
from facerec.util import asColumnMatrix
File "../../facerec/util.py", line 10, in <module>
import PIL
ImportError: No module named PIL

Please help me out with this.

**Comment by BarbaL** [comment]
You can try:
`pip install Pillow`
Then, after
`pip install PIL`

Install these packages and tell us the results.

**Comment by Anish-Jain** [comment]
I get the following output when I run the above commands -

pi@raspberrypi:~ $ pip install Pillow
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages
pi@raspberrypi:~ $ pip install PIL
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL

i.e, I'm able to install Pillow but not PIL.

**Comment by BarbaL** [comment]
Check in the train script if you are importing the PIL or the Pillow.

Where have
`import PIL`

change to
`from Pillow import PIL`

See more in [this issue](https://github.com/bytefish/facerec/issues/46)
